version: 0.0
os: linux
files:
  - source: ./dist/
    destination: /home/ubuntu/ida-authentication-api/dist/

  - source: ./package.json
    destination: /home/ubuntu/ida-authentication-api/
 
  - source: ./server-files/
    destination: /lib/systemd/system/

hooks:
  BeforeInstall:
    - location: ./scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: ./scripts/application_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: ./scripts/application_start.sh
      timeout: 300
      runas: root